import CircuiteFoundation
import Foundation

public protocol LogicUnboundedTemporalEquivalenceFoundationEngine:
    Engine<LogicUnboundedTemporalEquivalenceFoundationRequest, LogicUnboundedTemporalEquivalenceFoundationResult>
{}
